// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherActivityPlanner.Data;

#nullable disable

namespace WeatherActivityPlanner.Migrations
{
    [DbContext(typeof(WeatherPlannerDbContext))]
    [Migration("20260913182325_InitialSavedActivityPlans")]
    partial class InitialSavedActivityPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherActivityPlanner.Models.SavedActivityPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("PrecipitationMm")
                        .HasColumnType("float");

                    b.Property<string>("SuggestionDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SuggestionSeverity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SuggestionTitle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeedKmh")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SavedActivityPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
